---
fail_fast: false

default_stages:
  - commit
  - push

repos:
  - repo: https://github.com/thlorenz/doctoc
    rev: v2.2.0
    hooks:
      - id: doctoc
        args:
          - --update-only
          - --maxlevel
          - "3"
          - --github
          - --notitle

  - repo: https://github.com/adrienverge/yamllint
    rev: v1.36.2
    hooks:
      - id: yamllint
        args:
          - --config-file
          - .yamllint.yaml
        exclude: (pnpm-lock\.yaml)

  - repo: https://github.com/Lucas-C/pre-commit-hooks
    rev: v1.5.5
    hooks:
      - id: remove-crlf
        exclude: (dist/.*)
      - id: remove-tabs
        exclude: (dist/.*)

  - repo: https://github.com/sirosen/texthooks
    rev: 0.6.8
    hooks:
      - id: fix-smartquotes
        exclude: (dist/.*)
      - id: fix-ligatures
      - id: forbid-bidi-controls

  - repo: https://github.com/k8s-at-home/sops-pre-commit
    rev: v2.1.1
    hooks:
      - id: forbid-secrets

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: check-merge-conflict
      - id: check-added-large-files
        args:
          - --maxkb=100
        exclude: (dist/.*|pnpm-lock\.yaml)
      - id: check-case-conflict
      - id: check-executables-have-shebangs
      - id: check-json
      - id: check-symlinks
      - id: check-xml
      - id: detect-aws-credentials
        args:
          - --allow-missing-credentials
      - id: detect-private-key
        exclude: (dist/.*)
      - id: end-of-file-fixer
      - id: fix-byte-order-marker
      - id: mixed-line-ending
        exclude: (dist/.*)
        args:
          - --fix=auto
      - id: trailing-whitespace
        exclude: (dist/.*)
        args:
          - --markdown-linebreak-ext=md

  - repo: https://github.com/igorshubovych/markdownlint-cli
    rev: v0.44.0
    hooks:
      - id: markdownlint-fix
        args:
          - --config
          - .markdownlint.yaml

  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v3.1.0
    hooks:
      - id: prettier
        args:
          - --ignore-path
          - .prettierignore
          - --config
          - .prettierrc.js

  - repo: https://github.com/zricethezav/gitleaks
    rev: v8.24.2
    hooks:
      - id: gitleaks
