---
name: Publish Docker image

on:
  push:
    tags: ["v*.*.*", "v*.*.*-.*"]

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build:
    permissions:
      contents: read
      id-token: write
      packages: write
    runs-on: ubuntu-latest

    steps:
      # https://github.com/marketplace/actions/checkout
      - name: Checkout repository
        uses: actions/checkout@v4.0.0

      # https://github.com/marketplace/actions/cosign-installer
      - name: Setup cosign
        if: github.event_name != 'pull_request'
        uses: sigstore/cosign-installer@v3.1.2

      # Workaround: https://github.com/docker/build-push-action/issues/461
      # https://github.com/marketplace/actions/docker-setup-qemu
      - name: Setup QEMU
        uses: docker/setup-qemu-action@v2.2.0

      # https://github.com/marketplace/actions/docker-setup-buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2.10.0

      # https://github.com/marketplace/actions/docker-login
      - name: Setup GHCR
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v2.2.0
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # https://github.com/marketplace/actions/docker-metadata-action
      - name: Extract Docker metadata
        id: meta
        uses: docker/metadata-action@v4.6.0
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}

      # https://github.com/marketplace/actions/build-and-push-docker-images
      - name: Build and push Docker image
        id: build-and-push
        uses: docker/build-push-action@v4.2.1
        with:
          context: .
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

      # https://github.com/sigstore/cosign
      - name: Sign the published Docker image
        if: ${{ github.event_name != 'pull_request' }}
        # env:
        #   COSIGN_EXPERIMENTAL: "true"
        #   run: cosign sign ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}@${{ steps.build-and-push.outputs.digest }}
        # - name: Sign the images with GitHub OIDC Token
        run: echo "${{ steps.meta.outputs.tags }}" | xargs -I {} cosign sign --yes {}@${{ steps.build-and-push.outputs.digest }}
