---
# This workflow will do a clean installation of node dependencies, cache/restore them,
# build the source code and run tests across different versions of node

name: npm run lint

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # https://github.com/actions/checkout
      - name: checkout
        uses: actions/checkout@v3

      # https://github.com/marketplace/actions/setup-node-js-environment
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version-file: .nvmrc
          cache: npm
      - run: npm ci
      - run: npm run lint
